---
- hosts: all
  become: yes

  tasks:
    - name: Update apt and install dependencies
      apt:
        update_cache: yes
        name: "{{ item }}"
        state: present
      with_items:
        - nginx
        - python3-pip

    - name: Install Prometheus
      apt:
        name: prometheus
        state: present

    - name: Add Grafana APT key
      apt_key:
        url: https://packages.grafana.com/gpg.key
        state: present

    - name: Add Grafana APT repository
      apt_repository:
        repo: 'deb https://packages.grafana.com/oss/deb stable main'
        state: present
        filename: grafana

    - name: Update apt cache after adding Grafana repository
      apt:
        update_cache: yes

    - name: Install Grafana
      apt:
        name: grafana
        state: present

    - name: Start and enable Nginx
      service:
        name: nginx
        state: started
        enabled: yes

    - name: Start and enable Prometheus
      service:
        name: prometheus
        state: started
        enabled: yes

    - name: Start and enable Grafana
      service:
        name: grafana-server
        state: started
        enabled: yes
